export const GAMES_GENERATE_PRIME_NUMBERS = 'GAMES_GENERATE_PRIME_NUMBERS';
export const GAMES_GET_FIRST_NUMBER = 'GAMES_GET_FIRST_NUMBER';
export const GAMES_GET_SECOND_NUMBER = 'GAMES_GET_SECOND_NUMBER';